package com.api.model;
/**
 * TblMessage generated by hbm2java
 */
public class TblMessage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2637223720241933110L;
	private Integer messageId;
	private String message;
	private String expiresTime;
	private Integer senderId;
	private Integer userId;

	public TblMessage() {
	}

	public TblMessage(String expiresTime) {
		this.expiresTime = expiresTime;
	}

	public TblMessage(String message, String expiresTime, Integer senderId, Integer userId) {
		this.message = message;
		this.expiresTime = expiresTime;
		this.senderId = senderId;
		this.userId = userId;
	}

	public Integer getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getExpiresTime() {
		return this.expiresTime;
	}

	public void setExpiresTime(String expiresTime) {
		this.expiresTime = expiresTime;
	}

	public Integer getSenderId() {
		return this.senderId;
	}

	public void setSenderId(Integer senderId) {
		this.senderId = senderId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
