package com.api.model;
/**
 * TblUser generated by hbm2java
 */
public class TblUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3504760844520828430L;
	private Integer userId;
	private String userName;
	private String password;
	private String registrationId;

	public TblUser() {
	}

	public TblUser(String userName, String password, String registrationId) {
		this.userName = userName;
		this.password = password;
		this.registrationId = registrationId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRegistrationId() {
		return this.registrationId;
	}

	public void setRegistrationId(String registrationId) {
		this.registrationId = registrationId;
	}

}
